apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        imagePullPolicy: IfNotPresent
        image: vexrem/python-flask-example:latest
        ports:
        - containerPort: 5000
