# web-app-v2-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-app-v2-service
spec:
  selector:
    app: web-app
    version: v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP