apiVersion: v1
kind: Service
metadata:
  name: web-app-v1-service
spec:
  selector:
    app: web-app
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP